config/routes.rb
Rails.application.routes.draw do
  # ログインセッション(まだ使わない)
  get 'mypage', to: 'users#me'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # 掲示板サイトパス
  root 'boards#index'
  
  resources :users, only: %i[new create]
  resources :boards
  resources :comments, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  body       :text
#  name       :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Board < ApplicationRecord
	has_many :comments, dependent: :delete_all
	has_many :board_tag_relations, dependent: :delete_all
	has_many :tags, through: :board_tag_relations
	
	validates :name, presence: true, length: { maximum: 10 }
	validates :title, presence: true, length: { maximum: 30 }
	validates :body, presence: true, length: { maximum: 1000 }
end

app/models/board_tag_relation.rb
# == Schema Information
#
# Table name: board_tag_relations
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer
#  tag_id     :integer
#
# Indexes
#
#  index_board_tag_relations_on_board_id  (board_id)
#  index_board_tag_relations_on_tag_id    (tag_id)
#

class BoardTagRelation < ApplicationRecord
  belongs_to :board
  belongs_to :tag
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  comment    :text             not null
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer
#
# Indexes
#
#  index_comments_on_board_id  (board_id)
#

class Comment < ApplicationRecord
  belongs_to :board

  validates :name, presence: true, length: { maximum: 10 }
  validates :comment, presence: true, length: { maximum: 1000 }
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
	has_many :board_tag_relations, dependent: :delete_all
	has_many :boards, through: :board_tag_relations
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_name  (name) UNIQUE
#

class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# has_secure_password

	# validates :name,
	# 	presense: true,
	# 	uniquness: true,
	# 	length: { maximum: 16 },
	# 	format: {
	# 		with: /\A[a-z0-9]+\z/,
	# 		messege: 'は小文字大文字で入力してください'
	# 	}
	# 	validates :password,
	# 		length: { minimum: 8 }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	before_action :set_target_board, only: %i[show edit update destroy]

	def index
		# tagから紐づいている掲示板を表示
		@boards = params[:tag_id].present? ?Tag.find(params[:tag_id]).boards : Board.all
		#掲示板データの取得@boards変数に格納
		@boards = @boards.page(params[:page])
	end
	
	def new
		#新規に掲示板データを作成
		@board = Board.new(flash[:board])
	end

	def create
		#board_paramsに格納されているデータを元に掲示板作成
		board = Board.new(board_params)
		if board.save
			flash[:notice] = "「#{board.title}」の掲示板を作成しました"
			redirect_to board
		else
			redirect_to new_board_path, flash: {
				board: board,
				error_messages: board.errors.full_messages
			}
		end
	end

	def show
		#boardテーブルに紐づいてコメントテーブルを生成
		@comment = Comment.new(board_id: @board.id)
	end
	
	def edit 
	end

	def update 
		@board.update(board_params)
		redirect_to @board
	end

	def destroy
		@board.destroy
		flash[:notice] = "「#{@board.title}」の掲示板を削除されました"
		redirect_to boards_path
	end
	private

	#paramsの中のboardテーブルにあるname,title,bodyの値のみを取得するように明示している
	def board_params
		params.require(:board).permit(:name, :title, :body, tag_ids: [])
	end

	def set_target_board
		@board = Board.find(params[:id])
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      flash[:notice] = 'コメントを投稿しました'
      redirect_to comment.board
    else
      redirect_back fallback_location: root_path, flash: {
        comment: comment,
        error_messages: comment.errors.full_messages
      }
    end
  end

  def show
    @comment = Comment.new(board_id: @board.new)
  end
  
  def destroy
    comment = Comment.find(params[:id])
    comment.delete
    redirect_to comment.board, flash: {
      notice: 'コメントが削除されました'
    }
  end

  private

  def comment_params
    params.require(:comment).permit(:board_id, :name, :comment)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
  end

  def me
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<nav class="navbar" role="navigation" aria-labal="main navigation">
	<div class="navbar-brand">
		<a class="navbar-item" href="#">
			<h1 class="title">Djeeta</h1>
		</a>
		<div class="tabs ">
			<ul>
				<li class="is-active">  </li>
				<li ></li>
			</ul> 
		</div>
	</div>
</nav>

app/views/boards/_comment_form.html.erb
<%= render 'shared/error_messages'%>
<br>
<h1 class="title is-5" >
	コメント記入
</h1>
<%= form_for comment do |f| %>
	<%= f.hidden_field :board_id %>
	<form is-desktop>
		<div class="field">
			<label class="label">
				<%= f.label :name, '名前' %>
			</label>
			<div class="control">
				<%= f.text_field :name, class: 'input', placeholder: '名前を入力してください' %>
			</div>
		</div>
		<div class="field">
			<label class="label">
				<%= f.label :comment, '本文' %>
			</label>
			<div class="control">
				<%= f.text_area :comment, class: 'textarea is-medium', placeholder: 'コメントを入力してください' %>
			</div>
			<br>
			<div class="buttons has-addons is-center">
				<%= f.submit '送信', class: "button is-info" %>
			</div> 
		</div>
	</form>
<% end %>

app/views/boards/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_for board do |f| %>
	<form>
			<div class="field">
				<label class="label">
					<%= f.label :name, '名前' %>
				</label>
				<div class="control">
					<%= f.text_field :name, class: 'input', placeholder: '名前を入力してください' %>
				</div>
			<div class="field">
				<label class="label">
					<%= f.label :title, 'タイトル' %>
				</label>
				<div class="control">
					<%= f.text_field :title, class: 'input', placeholder: 'タイトルを入力してください' %>
				</div>
			</div>
			<div class="field">
				<label class="label">
					<%= f.label :body, '本文' %>
				</label>
				<div class="control">
					<%= f.text_area :body, class: 'textarea is-medium', placeholder: '本文を入力してください' %>
				</div>
			</div>
			<br>
			<span>タグ一覧</span>
			<br>
			<%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
				<span>
					<%= tag.label class: 'tag' do %>
						<%= tag.check_box class: 'checkbox' %>
						<%= tag.text %>
					<% end %>
				</span>
			<% end %>
				</label>
			<div class="buttons has-addons is-center">
				<%= f.submit '保存', class: "button is-info" %>
			</div> 
		</form>
<% end %>

app/views/boards/edit.html.erb
<div class="container">
	<section class="hero is-light">
		<div class="hero-body">
			<h1 class="title">
				掲示板編集
			</h1>
		</div>
	</section>
	<div class="buttons has-addons is-right">
		<button class="button">
			<%= link_to '掲示板一覧へ戻る', boards_path %>
		</button>
	</div>
		<%= render partial: 'form', locals: { board: @board } %>
</div>

app/views/boards/index.html.erb
<section class="hero is-light">
	<div class="hero-body">
		<h1 class="title">
			掲示板一覧
		</h1>
	</div>
</section>
	<%= form_tag boards_path, method: :get, class: 'boards_searchForm' do %>
			<%= select_tag :tag_id,
							options_from_collection_for_select(Tag.all, :id, :name, params[:tad_id]),
								{
									prompt: 'タグで絞り込み',
									class: 'form-control boards_select',
									onchange: 'submit(this.form);'
								} %>
			<% end %>
<div class="buttons has-addons is-right">
	<button class="button">
		<%= link_to '新規作成', new_board_path %>
	</button>
</div>

<% if flash[:notice] %>
	<div>
		<div class="notification is-danger">
			<%= flash[:notice]%>
		</div>
	</div>
<% end %>

<table class="table is-fullwidth is-right">
	<thead>
		<tr>
			<th>ID</th>
			<th>タイトル</th>
			<th>作成者</th>
			<th>作成日時</th>
			<th>更新日時</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @boards.each do |board| %>
			<tr>
				<td><%= board.id %></td>
				<td><%= board.title %></td>
				<td><%= board.name %></td>
				<td><%= board.created_at.to_s(:datetime_jp) %></td>
				<td><%= board.updated_at.to_s(:datetime_jp) %></td>
				<td>
					<button class="button is-link is-light">
						<%= link_to '詳細', board %>
					</button>
				</td>
				<td>
					<button class="button is-link is-light">
						<%= link_to '削除', board, method: :delete %>
					</button>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

	<%= paginate @boards %>

<br>
<br>

app/views/boards/new.html.erb
<div class="container">
	<section class="hero is-light">
		<div class="hero-body">
			<h1 class="title">
				掲示板作成
			</h1>
		</div>
	</section>
	<div class="buttons has-addons is-right">
		<button class="button">
			<%= link_to '掲示板一覧へ戻る', root_path %>
		</button>
	</div>
	<%= form_for @board do |f| %>
		<form>
			<div class="field">
				<label class="label">
					<%= f.label :name, '名前' %>
				</label>
				<div class="control">
					<%= f.text_field :name, class: 'input', placeholder: '名前を入力してください' %>
				</div>
			<div class="field">
				<label class="label">
					<%= f.label :title, 'タイトル' %>
				</label>
				<div class="control">
					<%= f.text_field :title, class: 'input', placeholder: 'タイトルを入力してください' %>
				</div>
			</div>
			<div class="field">
				<label class="label">
					<%= f.label :body, '本文' %>
				</label>
				<div class="control">
					<%= f.text_area :body, class: 'textarea is-medium', placeholder: '本文を入力してください' %>
				</div>
			</div>
			<div class="buttons has-addons is-center">
				<%= f.submit '保存', class: "button is-info" %>
			</div> 
		</form>
	<% end %>
</div>

app/views/boards/show.html.erb
<div class="container">
<div class="buttons has-addons is-right">
  <button class="button is-right">
    <%= link_to '掲示板一覧' , boards_path%>  
  </button>
</div>

  <% if flash[:notice] %>
		<div class="notification is-primary is-light">
			<%= flash[:notice] %>
		</div>
	<% end %> 

<div class="card">
  <header class="card-header">
    <p class="card-header-title">
      <%= @board.title %>
      <% @board.tags.each do |tag| %>
        <span class="tag is-light"> <%= tag.name %> </span>
      <% end %>
    </p>
		<div class="media">
			<div class="media-left">
				<p class="title is-5">
        <br>
					<%= @board.name %>
				</p>
			</div>
		</div>
  </header>
  <div class="card-content">
    <div class="content">
      <%= simple_format(@board.body) %>
      <br>
      <%= @board.created_at.to_s(:datetime_jp) %>
    </div>
  </div>

  <footer class="card-footer">
    <p class="card-footer-item"><%= link_to '編集', edit_board_path(@board) %></p>

  </footer>
</div>
<br>
<div class="title is-5">コメント</div>
  <%= render @board.comments %>
<%= render partial: 'comment_form', locals: { comment: @comment } %>
</div>

app/views/comments/_comment.html.erb
<article class="media">
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= comment.name %></strong> <small></small> 
        <br>
        <%= simple_format(comment.comment) %>
				<%= comment.created_at.to_s(:datetime_jp) %>
        <br>
       <small>
        <%= link_to '削除', comment, method: :delete, data: {
          confirm: '削除してもよろしいですか？' 
        } %>
       </small>
      </p>
		</div>
	</div>	
</article>
  

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/home/index.html.erb
<p>ユーザーが最初に訪れるページ</p>
<p>ログインしている状態としてない状態で処理を切り分ける</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Djeeta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1"> 

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.0/js/all.js"></script>
  </head>

  <body>
    <%= render 'header' %>
    <div class='container'> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if flash[:error_messages] %>
	<div class="notification is-danger">
		<ul>
			<% flash[:error_messages].each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/me.html.erb
<h1>Users#me</h1>
<p>Find me in app/views/users/me.html.erb</p>
// ユーザー用のマイページ